### ISSUE TITLE
not shown Reviews

### ISSUE THREAD

**Issue by Sinnocon** [PROGRAP/sw6-google-customer-reviews#29]
Hi,

is it correct, that with your Plugin for Shopware6 Google **MyBusiness** Reviews will be shown?! and not customer reviews from Google Merchant Center?

Which Maps API ID we need?

- Maps JavaScript API?

We've the problem, that our Google My Business reviews will not shown in the badge inspite of Google Maps API ID and Maps ID of our company.

Best Regards
Thomas

**Comment by TitanNano** [comment]
> Which Maps API ID we need?
>
> -    Maps JavaScript API?

Yes thats the right API.

> is it correct, that with your Plugin for Shopware6 Google MyBusiness Reviews will be shown?

Yes google my business reviews will be displayed. You have to use the placeId of your business on google maps. The input fields help text in the app settings should contain a link to googles place id finder tool.

**Comment by Sinnocon** [comment]
I used Maps JavaScript API Key from google cloud console, and correct google place id.
we are currently testing it on our test environment. But it still always will not be shown?!

Do we have to bring to production environment?

Thanks in advance.

**Comment by TitanNano** [comment]
- If the badge doesn't show up at all, then there is a template issue
- if the badge is displayed but only has three stars (one empty, one half and one full) then there is a JS issue, most likely the Google Maps API is not correctly loaded
- if the badge shows up but displays an empty rating (five empty stars) then there are either no reviews available or the wrong palceId is being loaded

The app should work anywhere no matter if it's a staging or a production environment. You can limit the Google Maps API to certian domains though. If the API has been restricted, then it won't work on other domains.

**Comment by Sinnocon** [comment]
ChIJO_X65CLGCUcRghHCo5GWM2k

https://www.google.com/maps/place/LED+Universum/@51.0823222,13.6384137,15z/data=!4m2!3m1!1s0x0:0x69339691a3c21182?sa=X&ved=2ahUKEwj0-aPj5KT3AhX1SPEDHWEOB-4Q_BJ6BQi7ARAF

this place_id and Google Maps / Business

so where is our mistake?

**Comment by TitanNano** [comment]
I get a 5-star rating back from the API for that place ID. So, there is either an issue with the Google Maps API itself (invalid API key, restricted API key, wrong API key) or an incompatibility with your shopware theme. This app is entirely browser-based, so you should be able to see errors in your browser console. If there is a loading issue for the maps API, then that should show up in your network manager.

**Comment by Sinnocon** [comment]
Thanks.

here is the error in console:
"Uncaught (in promise) Error: Google Maps API Library is not available!"

**Comment by Sinnocon** [comment]
is it already possible to use the badge as floating bagde at the right site of the page?

**Comment by TitanNano** [comment]
> Thanks.
> 
> here is the error in console: "Uncaught (in promise) Error: Google Maps API Library is not available!"

This indicates that you have enabled the option to not load the GoogleMaps API. When you enable this option, you have to load the Google Maps API yourself. 

https://github.com/PROGRAP/sw6-google-customer-reviews/blob/1f57cd4baff6ba6b786f05b7efa49c891b901848/Resources/app/storefront/src/plugin/pro-customer-reviews.plugin.js#L121-L131

> is it already possible to use the badge as floating bagde at the right site of the page?

no.

**Comment by Sinnocon** [comment]
Hey,

i have enabled the libaries now.

next issue
https://monosnap.com/file/ItcHsctLuH9NKiAPw137Cr2tOOT3My

although the java maps api is activated?

https://monosnap.com/file/HXkzOSxgzK3uXZvE7JVtoIm3LVoxdu

also the cloud account and search console owner is the same

**Comment by Sinnocon** [comment]
we have to use places API !
it works now
thanks
